version: '3.9'


networks:
  demo:
    driver: bridge

services:

  postgres:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: a123456789
      POSTGRES_DB: demo
    volumes:
      - ./data/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - demo


  pgadmin:
    image: dpage/pgadmin4:7.0
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: a123456789
      PGADMIN_DEFAULT_EMAIL: test@test.com
    volumes:
      - ./data/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - demo
